import {Open_Sans} from 'next/font/google'

const openSans = Open_Sans({
  subsets: ['latin'],
  weights: [400]
})
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({children}){
  return(
    <html lang='en' className={openSans.className}>
      <head />
      <body>{children}</body>
    </html>
  )
}
